export type ComponentControlValue = string | number | boolean;

export interface ComponentControlOption {
  label: string;
  value: string;
}

export interface ComponentControl {
  key: string;
  label: string;
  type: "text" | "textarea" | "slider" | "toggle" | "select" | "color";
  min?: number;
  max?: number;
  step?: number;
  options?: ComponentControlOption[];
}

export interface ComponentEntry {
  slug: string;
  title: string;
  category: string;
  description: string;
  sourcePath: string;
  order: number;
  tags?: string[];
  controls?: ComponentControl[];
  initialState?: Record<string, ComponentControlValue>;
}

export const categoryOrder = [
  "Actions",
  "Forms & Feedback",
  "Cards & Surfaces",
  "Overlays & Menus",
  "Layout & Navigation",
  "Typography & Counters",
  "Backgrounds & Ambient Effects",
  "3D & WebGL",
] as const;

export const componentRegistry: ComponentEntry[] = [
  {
    slug: "button",
    title: "Button",
    category: "Actions",
    description: "The core button primitive with variants, sizes, and disabled states.",
    sourcePath: "components/ui/button.tsx",
    order: 10,
    tags: ["action", "variant", "cta"],
    initialState: { label: "Test Me", variant: "default", size: "default", disabled: false },
    controls: [
      { key: "label", label: "Label", type: "text" },
      {
        key: "variant",
        label: "Variant",
        type: "select",
        options: [
          { label: "Default", value: "default" },
          { label: "Secondary", value: "secondary" },
          { label: "Outline", value: "outline" },
          { label: "Ghost", value: "ghost" },
          { label: "Destructive", value: "destructive" },
          { label: "Link", value: "link" },
        ],
      },
      {
        key: "size",
        label: "Size",
        type: "select",
        options: [
          { label: "Default", value: "default" },
          { label: "Small", value: "sm" },
          { label: "Large", value: "lg" },
        ],
      },
      { key: "disabled", label: "Disabled", type: "toggle" },
    ],
  },
  {
    slug: "shimmer-button",
    title: "Shimmer Button",
    category: "Actions",
    description: "A premium button with a conic shimmer sweep and layered lighting.",
    sourcePath: "components/ui/shimmer-button.tsx",
    order: 20,
    tags: ["button", "shimmer", "animated"],
    initialState: {
      label: "Test Me",
      shimmerColor: "#ffffff",
      shimmerDuration: 3,
      borderRadius: 24,
    },
    controls: [
      { key: "label", label: "Label", type: "text" },
      { key: "shimmerColor", label: "Shimmer color", type: "color" },
      { key: "shimmerDuration", label: "Duration", type: "slider", min: 1.5, max: 8, step: 0.5 },
      { key: "borderRadius", label: "Radius", type: "slider", min: 12, max: 999, step: 1 },
    ],
  },
  {
    slug: "magnetic-button",
    title: "Magnetic Button",
    category: "Actions",
    description: "Cursor-reactive movement that adds a tactile pull to any child button.",
    sourcePath: "components/ui/magnetic-button.tsx",
    order: 30,
    tags: ["button", "motion", "hover"],
    initialState: { label: "Test Me", strength: 0.35 },
    controls: [
      { key: "label", label: "Label", type: "text" },
      { key: "strength", label: "Strength", type: "slider", min: 0.1, max: 0.7, step: 0.05 },
    ],
  },
  {
    slug: "ripple-button",
    title: "Ripple Button",
    category: "Actions",
    description: "A soft expanding ripple that responds to the click position.",
    sourcePath: "components/ui/ripple-button.tsx",
    order: 40,
    tags: ["button", "feedback"],
    initialState: { label: "Test Me", rippleColor: "#ffffff" },
    controls: [
      { key: "label", label: "Label", type: "text" },
      { key: "rippleColor", label: "Ripple color", type: "color" },
    ],
  },
  {
    slug: "rainbow-button",
    title: "Rainbow Button",
    category: "Actions",
    description: "A saturated rainbow border treatment with a soft spectral glow.",
    sourcePath: "components/ui/rainbow-button.tsx",
    order: 50,
    tags: ["button", "gradient"],
    initialState: { label: "Test Me" },
    controls: [{ key: "label", label: "Label", type: "text" }],
  },
  {
    slug: "badge",
    title: "Badge",
    category: "Actions",
    description: "Compact status chips for labels, release notes, or category tags.",
    sourcePath: "components/ui/badge.tsx",
    order: 60,
    tags: ["label", "status"],
    initialState: { label: "New release", variant: "gradient" },
    controls: [
      { key: "label", label: "Label", type: "text" },
      {
        key: "variant",
        label: "Variant",
        type: "select",
        options: [
          { label: "Default", value: "default" },
          { label: "Secondary", value: "secondary" },
          { label: "Outline", value: "outline" },
          { label: "Success", value: "success" },
          { label: "Warning", value: "warning" },
          { label: "Gradient", value: "gradient" },
        ],
      },
    ],
  },
  {
    slug: "switch",
    title: "Switch",
    category: "Forms & Feedback",
    description: "A springy toggle with clear active, inactive, and disabled states.",
    sourcePath: "components/ui/switch.tsx",
    order: 10,
    tags: ["toggle", "form"],
    initialState: { checked: true, disabled: false },
    controls: [
      { key: "checked", label: "Checked", type: "toggle" },
      { key: "disabled", label: "Disabled", type: "toggle" },
    ],
  },
  {
    slug: "floating-input",
    title: "Floating Input",
    category: "Forms & Feedback",
    description: "A text field with an animated label that lifts as content appears.",
    sourcePath: "components/ui/floating-input.tsx",
    order: 20,
    tags: ["form", "input"],
    initialState: { label: "Email address", type: "email", disabled: false },
    controls: [
      { key: "label", label: "Label", type: "text" },
      {
        key: "type",
        label: "Type",
        type: "select",
        options: [
          { label: "Text", value: "text" },
          { label: "Email", value: "email" },
          { label: "Password", value: "password" },
        ],
      },
      { key: "disabled", label: "Disabled", type: "toggle" },
    ],
  },
  {
    slug: "input",
    title: "Input",
    category: "Forms & Feedback",
    description: "A styled text input primitive for forms, filters, and search fields.",
    sourcePath: "components/ui/input.tsx",
    order: 25,
    tags: ["form", "input"],
    initialState: { placeholder: "Enter your email", disabled: false },
    controls: [
      { key: "placeholder", label: "Placeholder", type: "text" },
      { key: "disabled", label: "Disabled", type: "toggle" },
    ],
  },
  {
    slug: "textarea",
    title: "Textarea",
    category: "Forms & Feedback",
    description: "Multi-line text input with matching Aurora styling and focus states.",
    sourcePath: "components/ui/textarea.tsx",
    order: 26,
    tags: ["form", "textarea"],
    initialState: { placeholder: "Write something...", rows: 4 },
    controls: [
      { key: "placeholder", label: "Placeholder", type: "text" },
      { key: "rows", label: "Rows", type: "slider", min: 2, max: 8, step: 1 },
    ],
  },
  {
    slug: "progress",
    title: "Progress",
    category: "Forms & Feedback",
    description: "A fluid progress bar with optional multicolor gradient fill.",
    sourcePath: "components/ui/progress.tsx",
    order: 30,
    tags: ["feedback", "loading"],
    initialState: { value: 68, gradient: true },
    controls: [
      { key: "value", label: "Value", type: "slider", min: 0, max: 100, step: 1 },
      { key: "gradient", label: "Gradient", type: "toggle" },
    ],
  },
  {
    slug: "tooltip",
    title: "Tooltip",
    category: "Forms & Feedback",
    description: "Directional tooltips for adding quick context around interactions.",
    sourcePath: "components/ui/tooltip.tsx",
    order: 40,
    tags: ["hover", "overlay"],
    initialState: { content: "I follow your cursor", side: "top" },
    controls: [
      { key: "content", label: "Content", type: "text" },
      {
        key: "side",
        label: "Side",
        type: "select",
        options: [
          { label: "Top", value: "top" },
          { label: "Bottom", value: "bottom" },
          { label: "Left", value: "left" },
          { label: "Right", value: "right" },
        ],
      },
    ],
  },
  {
    slug: "checkbox",
    title: "Checkbox",
    category: "Forms & Feedback",
    description: "Accessible checkbox built on Radix with Aurora focus and checked states.",
    sourcePath: "components/ui/checkbox.tsx",
    order: 45,
    tags: ["form", "toggle"],
    initialState: { checked: true, disabled: false },
    controls: [
      { key: "checked", label: "Checked", type: "toggle" },
      { key: "disabled", label: "Disabled", type: "toggle" },
    ],
  },
  {
    slug: "range-slider",
    title: "Slider",
    category: "Forms & Feedback",
    description: "Draggable range control with gradient fill and spring thumb.",
    sourcePath: "components/ui/slider.tsx",
    order: 46,
    tags: ["form", "range"],
    initialState: { value: 50, min: 0, max: 100 },
    controls: [
      { key: "value", label: "Value", type: "slider", min: 0, max: 100, step: 1 },
      { key: "min", label: "Minimum", type: "slider", min: 0, max: 90, step: 1 },
      { key: "max", label: "Maximum", type: "slider", min: 10, max: 100, step: 1 },
    ],
  },
  {
    slug: "select",
    title: "Select",
    category: "Forms & Feedback",
    description: "Keyboard-friendly select menu with animated open/close transitions.",
    sourcePath: "components/ui/select.tsx",
    order: 47,
    tags: ["form", "select"],
    initialState: { value: "design" },
    controls: [
      {
        key: "value",
        label: "Value",
        type: "select",
        options: [
          { label: "Design", value: "design" },
          { label: "Engineering", value: "engineering" },
          { label: "Marketing", value: "marketing" },
        ],
      },
    ],
  },
  {
    slug: "otp-input",
    title: "OTP Input",
    category: "Forms & Feedback",
    description: "Segmented one-time-password input with paste support and arrow navigation.",
    sourcePath: "components/ui/otp-input.tsx",
    order: 48,
    tags: ["form", "auth"],
    initialState: { length: 6, otp: "" },
    controls: [{ key: "length", label: "Length", type: "slider", min: 4, max: 8, step: 1 }],
  },
  {
    slug: "star-rating",
    title: "Star Rating",
    category: "Forms & Feedback",
    description: "Interactive star rating with hover preview and read-only mode.",
    sourcePath: "components/ui/star-rating.tsx",
    order: 49,
    tags: ["form", "rating"],
    initialState: { value: 3, readOnly: false, size: "md" },
    controls: [
      { key: "value", label: "Value", type: "slider", min: 0, max: 5, step: 1 },
      { key: "readOnly", label: "Read only", type: "toggle" },
      {
        key: "size",
        label: "Size",
        type: "select",
        options: [
          { label: "Small", value: "sm" },
          { label: "Medium", value: "md" },
          { label: "Large", value: "lg" },
        ],
      },
    ],
  },
  {
    slug: "alert",
    title: "Alert",
    category: "Forms & Feedback",
    description: "Contextual callout banners for info, success, warning, and error states.",
    sourcePath: "components/ui/alert.tsx",
    order: 75,
    tags: ["feedback", "status"],
    initialState: {
      variant: "info",
      title: "Heads up",
      description: "You can customize this alert with variants and copy.",
    },
    controls: [
      {
        key: "variant",
        label: "Variant",
        type: "select",
        options: [
          { label: "Default", value: "default" },
          { label: "Info", value: "info" },
          { label: "Success", value: "success" },
          { label: "Warning", value: "warning" },
          { label: "Destructive", value: "destructive" },
        ],
      },
      { key: "title", label: "Title", type: "text" },
      { key: "description", label: "Description", type: "textarea" },
    ],
  },
  {
    slug: "accordion",
    title: "Accordion",
    category: "Forms & Feedback",
    description: "Animated disclosure panels for compact FAQ and settings layouts.",
    sourcePath: "components/ui/accordion.tsx",
    order: 50,
    tags: ["faq", "disclosure"],
    initialState: { allowMultiple: false },
    controls: [{ key: "allowMultiple", label: "Allow multiple", type: "toggle" }],
  },
  {
    slug: "animated-tabs",
    title: "Animated Tabs",
    category: "Forms & Feedback",
    description: "A sliding pill tabset powered by shared layout animation.",
    sourcePath: "components/ui/animated-tabs.tsx",
    order: 60,
    tags: ["tabs", "navigation"],
    initialState: { defaultTab: "design" },
    controls: [
      {
        key: "defaultTab",
        label: "Default tab",
        type: "select",
        options: [
          { label: "Design", value: "design" },
          { label: "Motion", value: "motion" },
          { label: "Delivery", value: "delivery" },
        ],
      },
    ],
  },
  {
    slug: "animated-modal",
    title: "Animated Modal",
    category: "Forms & Feedback",
    description: "A spring-based modal system with backdrop blur and layered motion.",
    sourcePath: "components/ui/animated-modal.tsx",
    order: 70,
    tags: ["modal", "overlay"],
    initialState: { label: "Open modal" },
    controls: [{ key: "label", label: "Trigger label", type: "text" }],
  },
  {
    slug: "spotlight-card",
    title: "Spotlight Card",
    category: "Cards & Surfaces",
    description: "A card surface that blooms with a radial spotlight under the cursor.",
    sourcePath: "components/ui/spotlight-card.tsx",
    order: 10,
    tags: ["card", "hover"],
    initialState: { spotlightColor: "#a855f7", spotlightOpacity: 0.18 },
    controls: [
      { key: "spotlightColor", label: "Spotlight color", type: "color" },
      { key: "spotlightOpacity", label: "Opacity", type: "slider", min: 0.05, max: 0.5, step: 0.01 },
    ],
  },
  {
    slug: "card",
    title: "Card",
    category: "Cards & Surfaces",
    description: "Composable card primitive with header, content, and footer sections.",
    sourcePath: "components/ui/card.tsx",
    order: 15,
    tags: ["card", "layout"],
    initialState: { title: "Project overview", description: "Track milestones and team progress.", showFooter: true },
    controls: [
      { key: "title", label: "Title", type: "text" },
      { key: "description", label: "Description", type: "textarea" },
      { key: "showFooter", label: "Show footer", type: "toggle" },
    ],
  },
  {
    slug: "avatar",
    title: "Avatar",
    category: "Cards & Surfaces",
    description: "User avatar with image support and gradient fallback initials.",
    sourcePath: "components/ui/avatar.tsx",
    order: 25,
    tags: ["profile", "avatar"],
    initialState: { fallback: "AU", size: "md" },
    controls: [
      { key: "fallback", label: "Fallback", type: "text" },
      {
        key: "size",
        label: "Size",
        type: "select",
        options: [
          { label: "Small", value: "sm" },
          { label: "Medium", value: "md" },
          { label: "Large", value: "lg" },
        ],
      },
    ],
  },
  {
    slug: "card-3d",
    title: "3D Card",
    category: "Cards & Surfaces",
    description: "A perspective tilt card with configurable motion intensity.",
    sourcePath: "components/ui/card-3d.tsx",
    order: 20,
    tags: ["card", "motion", "tilt"],
    initialState: { intensity: 12 },
    controls: [{ key: "intensity", label: "Intensity", type: "slider", min: 4, max: 24, step: 1 }],
  },
  {
    slug: "glow-card",
    title: "Glow Card",
    category: "Cards & Surfaces",
    description: "A border glow that tracks the mouse for connected grids and panels.",
    sourcePath: "components/ui/glow-card.tsx",
    order: 30,
    tags: ["card", "glow"],
    initialState: { glowColor: "#a855f7" },
    controls: [{ key: "glowColor", label: "Glow color", type: "color" }],
  },
  {
    slug: "border-beam",
    title: "Border Beam",
    category: "Cards & Surfaces",
    description: "A comet-like beam that traces the perimeter of a rounded surface.",
    sourcePath: "components/ui/border-beam.tsx",
    order: 40,
    tags: ["border", "beam"],
    initialState: { size: 220, duration: 8, colorFrom: "#a855f7", colorTo: "#22d3ee" },
    controls: [
      { key: "size", label: "Beam size", type: "slider", min: 120, max: 320, step: 10 },
      { key: "duration", label: "Duration", type: "slider", min: 4, max: 16, step: 1 },
      { key: "colorFrom", label: "From", type: "color" },
      { key: "colorTo", label: "To", type: "color" },
    ],
  },
  {
    slug: "skeleton",
    title: "Skeleton",
    category: "Cards & Surfaces",
    description: "A subtle shimmer placeholder for loading content blocks and avatars.",
    sourcePath: "components/ui/skeleton.tsx",
    order: 50,
    tags: ["loading", "placeholder"],
    initialState: { columns: 1, showAvatar: true },
    controls: [
      { key: "columns", label: "Columns", type: "slider", min: 1, max: 3, step: 1 },
      { key: "showAvatar", label: "Show avatar row", type: "toggle" },
    ],
  },
  {
    slug: "card-stack",
    title: "Card Stack",
    category: "Cards & Surfaces",
    description: "An auto-cycling layered stack that keeps the top card in focus.",
    sourcePath: "components/ui/card-stack.tsx",
    order: 60,
    tags: ["stack", "testimonials"],
    initialState: { interval: 4000, offset: 12 },
    controls: [
      { key: "interval", label: "Cycle interval (ms)", type: "slider", min: 2000, max: 8000, step: 500 },
      { key: "offset", label: "Stack offset", type: "slider", min: 6, max: 24, step: 2 },
    ],
  },
  {
    slug: "hover-card",
    title: "Hover Card",
    category: "Cards & Surfaces",
    description: "Rich preview card that appears on hover with smooth enter/exit motion.",
    sourcePath: "components/ui/hover-card.tsx",
    order: 65,
    tags: ["hover", "preview"],
    initialState: { name: "Ava Chen", role: "Design lead" },
    controls: [
      { key: "name", label: "Name", type: "text" },
      { key: "role", label: "Role", type: "text" },
    ],
  },
  {
    slug: "carousel",
    title: "Carousel",
    category: "Cards & Surfaces",
    description: "Animated slide carousel with arrows, dots, and optional autoplay.",
    sourcePath: "components/ui/carousel.tsx",
    order: 70,
    tags: ["carousel", "slides"],
    initialState: { autoPlay: false, interval: 4000 },
    controls: [
      { key: "autoPlay", label: "Auto play", type: "toggle" },
      { key: "interval", label: "Interval (ms)", type: "slider", min: 2000, max: 8000, step: 500 },
    ],
  },
  {
    slug: "dropdown-menu",
    title: "Dropdown Menu",
    category: "Overlays & Menus",
    description: "Context menu with items, shortcuts, and keyboard navigation.",
    sourcePath: "components/ui/dropdown-menu.tsx",
    order: 10,
    tags: ["menu", "overlay"],
    initialState: { triggerLabel: "Open menu" },
    controls: [{ key: "triggerLabel", label: "Trigger label", type: "text" }],
  },
  {
    slug: "popover",
    title: "Popover",
    category: "Overlays & Menus",
    description: "Floating panel anchored to a trigger for compact secondary content.",
    sourcePath: "components/ui/popover.tsx",
    order: 20,
    tags: ["overlay", "popover"],
    initialState: { title: "Dimensions", description: "Set the width and height for the layer." },
    controls: [
      { key: "title", label: "Title", type: "text" },
      { key: "description", label: "Description", type: "textarea" },
    ],
  },
  {
    slug: "sheet",
    title: "Sheet",
    category: "Overlays & Menus",
    description: "Spring-animated slide-over panel for settings, filters, and mobile nav.",
    sourcePath: "components/ui/sheet.tsx",
    order: 30,
    tags: ["drawer", "overlay"],
    initialState: { side: "right", title: "Quick settings" },
    controls: [
      {
        key: "side",
        label: "Side",
        type: "select",
        options: [
          { label: "Right", value: "right" },
          { label: "Left", value: "left" },
        ],
      },
      { key: "title", label: "Title", type: "text" },
    ],
  },
  {
    slug: "command-menu",
    title: "Command Menu",
    category: "Overlays & Menus",
    description: "Spotlight-style command palette with search and keyboard shortcuts.",
    sourcePath: "components/ui/command-menu.tsx",
    order: 40,
    tags: ["command", "search"],
    initialState: { placeholder: "Search commands..." },
    controls: [{ key: "placeholder", label: "Placeholder", type: "text" }],
  },
  {
    slug: "marquee",
    title: "Marquee",
    category: "Layout & Navigation",
    description: "An endlessly looping strip for logos, pills, or small content rows.",
    sourcePath: "components/ui/marquee.tsx",
    order: 10,
    tags: ["loop", "layout"],
    initialState: { reverse: false, pauseOnHover: true, repeat: 4, duration: 22 },
    controls: [
      { key: "reverse", label: "Reverse", type: "toggle" },
      { key: "pauseOnHover", label: "Pause on hover", type: "toggle" },
      { key: "repeat", label: "Repeat", type: "slider", min: 2, max: 6, step: 1 },
      { key: "duration", label: "Duration (s)", type: "slider", min: 10, max: 60, step: 2 },
    ],
  },
  {
    slug: "bento-grid",
    title: "Bento Grid",
    category: "Layout & Navigation",
    description: "A responsive editorial grid for mixing product stories and feature cards.",
    sourcePath: "components/ui/bento-grid.tsx",
    order: 20,
    tags: ["grid", "layout"],
    initialState: { rowHeight: 15 },
    controls: [{ key: "rowHeight", label: "Row height (rem)", type: "slider", min: 12, max: 20, step: 1 }],
  },
  {
    slug: "dock",
    title: "Dock",
    category: "Layout & Navigation",
    description: "A magnifying dock inspired by desktop launchers and app bars.",
    sourcePath: "components/ui/dock.tsx",
    order: 30,
    tags: ["navigation", "dock"],
    initialState: { magnification: 76 },
    controls: [{ key: "magnification", label: "Magnification", type: "slider", min: 48, max: 96, step: 4 }],
  },
  {
    slug: "infinite-moving-cards",
    title: "Infinite Moving Cards",
    category: "Layout & Navigation",
    description: "A testimonial rail built on top of the marquee primitive.",
    sourcePath: "components/ui/infinite-moving-cards.tsx",
    order: 40,
    tags: ["marquee", "testimonials"],
    initialState: { reverse: false, duration: 40 },
    controls: [
      { key: "reverse", label: "Reverse", type: "toggle" },
      { key: "duration", label: "Duration (s)", type: "slider", min: 15, max: 80, step: 5 },
    ],
  },
  {
    slug: "scroll-progress",
    title: "Scroll Progress",
    category: "Layout & Navigation",
    description: "A viewport-bound progress indicator that tracks page scroll.",
    sourcePath: "components/ui/scroll-progress.tsx",
    order: 50,
    tags: ["viewport", "progress"],
    initialState: { panelHeight: 360 },
    controls: [
      { key: "panelHeight", label: "Panel height", type: "slider", min: 240, max: 480, step: 20 },
    ],
  },
  {
    slug: "navbar",
    title: "Navbar",
    category: "Layout & Navigation",
    description: "Responsive top navigation with mobile drawer and CTA button.",
    sourcePath: "components/ui/navbar.tsx",
    order: 55,
    tags: ["navigation", "header"],
    initialState: { brand: "Aurora UI" },
    controls: [{ key: "brand", label: "Brand", type: "text" }],
  },
  {
    slug: "breadcrumb",
    title: "Breadcrumb",
    category: "Layout & Navigation",
    description: "Hierarchical breadcrumb trail for nested pages and settings.",
    sourcePath: "components/ui/breadcrumb.tsx",
    order: 60,
    tags: ["navigation", "breadcrumb"],
    initialState: { currentPage: "Typography" },
    controls: [{ key: "currentPage", label: "Current page", type: "text" }],
  },
  {
    slug: "pagination",
    title: "Pagination",
    category: "Layout & Navigation",
    description: "Numbered page controls with previous/next navigation.",
    sourcePath: "components/ui/pagination.tsx",
    order: 65,
    tags: ["navigation", "pagination"],
    initialState: { page: 1, totalPages: 5 },
    controls: [
      { key: "page", label: "Page", type: "slider", min: 1, max: 10, step: 1 },
      { key: "totalPages", label: "Total pages", type: "slider", min: 3, max: 10, step: 1 },
    ],
  },
  {
    slug: "gradient-text",
    title: "Gradient Text",
    category: "Typography & Counters",
    description: "Animated gradient typography for large headlines and accents.",
    sourcePath: "components/ui/gradient-text.tsx",
    order: 10,
    tags: ["headline", "gradient"],
    initialState: { label: "Aurora gradient", animate: true },
    controls: [
      { key: "label", label: "Text", type: "text" },
      { key: "animate", label: "Animate", type: "toggle" },
    ],
  },
  {
    slug: "shiny-text",
    title: "Shiny Text",
    category: "Typography & Counters",
    description: "A glossy text treatment with a subtle moving highlight.",
    sourcePath: "components/ui/shiny-text.tsx",
    order: 20,
    tags: ["headline", "shimmer"],
    initialState: { label: "Shiny text that catches the light", shimmerWidth: 100 },
    controls: [
      { key: "label", label: "Text", type: "text" },
      { key: "shimmerWidth", label: "Shimmer width", type: "slider", min: 60, max: 200, step: 10 },
    ],
  },
  {
    slug: "typewriter",
    title: "Typewriter",
    category: "Typography & Counters",
    description: "Typing and deleting copy for hero lines, taglines, and product loops.",
    sourcePath: "components/ui/typewriter.tsx",
    order: 30,
    tags: ["text", "typing"],
    initialState: {
      words: "websites, dashboards, experiences, the future",
      typingSpeed: 90,
      deletingSpeed: 45,
      pauseTime: 1600,
    },
    controls: [
      { key: "words", label: "Words", type: "textarea" },
      { key: "typingSpeed", label: "Typing speed", type: "slider", min: 40, max: 180, step: 5 },
      { key: "deletingSpeed", label: "Deleting speed", type: "slider", min: 20, max: 120, step: 5 },
      { key: "pauseTime", label: "Pause time", type: "slider", min: 500, max: 3000, step: 100 },
    ],
  },
  {
    slug: "text-reveal",
    title: "Text Reveal",
    category: "Typography & Counters",
    description: "Word-by-word reveals that activate as content enters the viewport.",
    sourcePath: "components/ui/text-reveal.tsx",
    order: 40,
    tags: ["scroll", "headline"],
    initialState: {
      text: "This reveal animates word by word as it enters the viewport.",
      delay: 0,
    },
    controls: [
      { key: "text", label: "Text", type: "textarea" },
      { key: "delay", label: "Delay", type: "slider", min: 0, max: 1.2, step: 0.05 },
    ],
  },
  {
    slug: "flip-words",
    title: "Flip Words",
    category: "Typography & Counters",
    description: "Inline word swaps that preserve layout while cycling through a set.",
    sourcePath: "components/ui/flip-words.tsx",
    order: 50,
    tags: ["hero", "text"],
    initialState: { words: "fluid, premium, tactile, playful", duration: 2500 },
    controls: [
      { key: "words", label: "Words", type: "textarea" },
      { key: "duration", label: "Duration", type: "slider", min: 1200, max: 4000, step: 100 },
    ],
  },
  {
    slug: "number-ticker",
    title: "Number Ticker",
    category: "Typography & Counters",
    description: "Animated figures for stats, dashboards, and compact metric cards.",
    sourcePath: "components/ui/number-ticker.tsx",
    order: 60,
    tags: ["metrics", "stats"],
    initialState: { value: 12840, direction: "up", decimalPlaces: 0, delay: 0 },
    controls: [
      { key: "value", label: "Value", type: "slider", min: 0, max: 25000, step: 50 },
      {
        key: "direction",
        label: "Direction",
        type: "select",
        options: [
          { label: "Up", value: "up" },
          { label: "Down", value: "down" },
        ],
      },
      { key: "decimalPlaces", label: "Decimals", type: "slider", min: 0, max: 2, step: 1 },
      { key: "delay", label: "Delay (s)", type: "slider", min: 0, max: 3, step: 0.1 },
    ],
  },
  {
    slug: "blur-text",
    title: "Blur Text",
    category: "Typography & Counters",
    description: "Characters or words animate in from blur with staggered timing.",
    sourcePath: "components/ui/blur-text.tsx",
    order: 65,
    tags: ["text", "animation"],
    initialState: { text: "Beautiful motion, built in.", delay: 50, animateBy: "chars", direction: "top" },
    controls: [
      { key: "text", label: "Text", type: "text" },
      { key: "delay", label: "Stagger (ms)", type: "slider", min: 20, max: 120, step: 10 },
      {
        key: "animateBy",
        label: "Animate by",
        type: "select",
        options: [
          { label: "Chars", value: "chars" },
          { label: "Words", value: "words" },
        ],
      },
      {
        key: "direction",
        label: "Direction",
        type: "select",
        options: [
          { label: "Top", value: "top" },
          { label: "Bottom", value: "bottom" },
        ],
      },
    ],
  },
  {
    slug: "split-text",
    title: "Split Text",
    category: "Typography & Counters",
    description: "Split and stagger text by characters, words, or lines with 3D rotation.",
    sourcePath: "components/ui/split-text.tsx",
    order: 70,
    tags: ["text", "hero"],
    initialState: { text: "Hello, you!", splitType: "chars", delay: 50, duration: 0.8 },
    controls: [
      { key: "text", label: "Text", type: "text" },
      {
        key: "splitType",
        label: "Split type",
        type: "select",
        options: [
          { label: "Chars", value: "chars" },
          { label: "Words", value: "words" },
        ],
      },
      { key: "delay", label: "Stagger (ms)", type: "slider", min: 20, max: 120, step: 10 },
      { key: "duration", label: "Duration (s)", type: "slider", min: 0.4, max: 1.6, step: 0.1 },
    ],
  },
  {
    slug: "countdown",
    title: "Countdown",
    category: "Typography & Counters",
    description: "Live countdown timer with animated digit transitions.",
    sourcePath: "components/ui/countdown.tsx",
    order: 75,
    tags: ["timer", "launch"],
    initialState: { showLabels: true },
    controls: [{ key: "showLabels", label: "Show labels", type: "toggle" }],
  },
  {
    slug: "fade-in",
    title: "Fade In",
    category: "Typography & Counters",
    description: "Scroll-triggered fade and blur entrance wrapper for any content.",
    sourcePath: "components/ui/fade-in.tsx",
    order: 80,
    tags: ["scroll", "reveal"],
    initialState: { direction: "up", blur: true, delay: 0 },
    controls: [
      {
        key: "direction",
        label: "Direction",
        type: "select",
        options: [
          { label: "Up", value: "up" },
          { label: "Down", value: "down" },
          { label: "Left", value: "left" },
          { label: "Right", value: "right" },
          { label: "None", value: "none" },
        ],
      },
      { key: "blur", label: "Blur", type: "toggle" },
      { key: "delay", label: "Delay (s)", type: "slider", min: 0, max: 1, step: 0.1 },
    ],
  },
  {
    slug: "aurora-background",
    title: "Aurora Background",
    category: "Backgrounds & Ambient Effects",
    description: "A living gradient field that gives pages atmosphere without heavy markup.",
    sourcePath: "components/ui/aurora-background.tsx",
    order: 10,
    tags: ["background", "aurora"],
    initialState: { showRadialGradient: true },
    controls: [{ key: "showRadialGradient", label: "Radial mask", type: "toggle" }],
  },
  {
    slug: "grid-pattern",
    title: "Grid Pattern",
    category: "Backgrounds & Ambient Effects",
    description: "Low-contrast grids or dots for grounded surfaces and hero backdrops.",
    sourcePath: "components/ui/grid-pattern.tsx",
    order: 20,
    tags: ["background", "pattern"],
    initialState: { variant: "grid", fade: true },
    controls: [
      {
        key: "variant",
        label: "Variant",
        type: "select",
        options: [
          { label: "Grid", value: "grid" },
          { label: "Dot", value: "dot" },
        ],
      },
      { key: "fade", label: "Fade mask", type: "toggle" },
    ],
  },
  {
    slug: "spotlight",
    title: "Spotlight",
    category: "Backgrounds & Ambient Effects",
    description: "An oversized, animated spotlight that energizes hero sections.",
    sourcePath: "components/ui/spotlight.tsx",
    order: 30,
    tags: ["background", "hero"],
    initialState: { fill: "#a855f7" },
    controls: [{ key: "fill", label: "Fill", type: "color" }],
  },
  {
    slug: "particles",
    title: "Particles",
    category: "Backgrounds & Ambient Effects",
    description: "A lightweight particle field for ambient motion and hover depth.",
    sourcePath: "components/ui/particles.tsx",
    order: 40,
    tags: ["canvas", "ambient"],
    initialState: { quantity: 60, speed: 0.45, color: "#a855f7" },
    controls: [
      { key: "quantity", label: "Quantity", type: "slider", min: 10, max: 120, step: 2 },
      { key: "speed", label: "Speed", type: "slider", min: 0.1, max: 1.2, step: 0.05 },
      { key: "color", label: "Color", type: "color" },
    ],
  },
  {
    slug: "meteors",
    title: "Meteors",
    category: "Backgrounds & Ambient Effects",
    description: "A meteor shower overlay for dramatic cards and promotional blocks.",
    sourcePath: "components/ui/meteors.tsx",
    order: 50,
    tags: ["background", "effect"],
    initialState: { number: 16 },
    controls: [{ key: "number", label: "Count", type: "slider", min: 6, max: 30, step: 1 }],
  },
  {
    slug: "radio-group",
    title: "Radio Group",
    category: "Forms & Feedback",
    description: "Single-select radio options with accessible keyboard navigation.",
    sourcePath: "components/ui/radio-group.tsx",
    order: 50,
    tags: ["form", "radio"],
    initialState: { value: "starter" },
    controls: [
      {
        key: "value",
        label: "Selected",
        type: "select",
        options: [
          { label: "Starter", value: "starter" },
          { label: "Pro", value: "pro" },
          { label: "Enterprise", value: "enterprise" },
        ],
      },
    ],
  },
  {
    slug: "toggle-group",
    title: "Toggle Group",
    category: "Forms & Feedback",
    description: "Segmented control for switching between a small set of views or filters.",
    sourcePath: "components/ui/toggle-group.tsx",
    order: 51,
    tags: ["form", "segmented"],
    initialState: { value: "week" },
    controls: [
      {
        key: "value",
        label: "Selected",
        type: "select",
        options: [
          { label: "Day", value: "day" },
          { label: "Week", value: "week" },
          { label: "Month", value: "month" },
        ],
      },
    ],
  },
  {
    slug: "password-input",
    title: "Password Input",
    category: "Forms & Feedback",
    description: "Password field with show/hide visibility toggle.",
    sourcePath: "components/ui/password-input.tsx",
    order: 52,
    tags: ["form", "auth"],
    initialState: { placeholder: "Enter password" },
    controls: [{ key: "placeholder", label: "Placeholder", type: "text" }],
  },
  {
    slug: "file-dropzone",
    title: "File Dropzone",
    category: "Forms & Feedback",
    description: "Drag-and-drop upload zone with file size limits.",
    sourcePath: "components/ui/file-dropzone.tsx",
    order: 53,
    tags: ["form", "upload"],
    initialState: { maxSizeMb: 10 },
    controls: [{ key: "maxSizeMb", label: "Max size (MB)", type: "slider", min: 1, max: 50, step: 1 }],
  },
  {
    slug: "spinner",
    title: "Spinner",
    category: "Forms & Feedback",
    description: "Animated loading indicator in three sizes.",
    sourcePath: "components/ui/spinner.tsx",
    order: 80,
    tags: ["loading", "feedback"],
    initialState: { size: "md" },
    controls: [
      {
        key: "size",
        label: "Size",
        type: "select",
        options: [
          { label: "Small", value: "sm" },
          { label: "Medium", value: "md" },
          { label: "Large", value: "lg" },
        ],
      },
    ],
  },
  {
    slug: "empty-state",
    title: "Empty State",
    category: "Forms & Feedback",
    description: "Placeholder for empty lists, search results, or first-run experiences.",
    sourcePath: "components/ui/empty-state.tsx",
    order: 85,
    tags: ["empty", "placeholder"],
    initialState: { title: "No results yet", description: "Try adjusting your filters or create something new.", actionLabel: "Create item" },
    controls: [
      { key: "title", label: "Title", type: "text" },
      { key: "description", label: "Description", type: "textarea" },
      { key: "actionLabel", label: "Action label", type: "text" },
    ],
  },
  {
    slug: "table",
    title: "Table",
    category: "Cards & Surfaces",
    description: "Styled data table with hover rows and compact typography.",
    sourcePath: "components/ui/table.tsx",
    order: 75,
    tags: ["data", "table"],
    initialState: { compact: false },
    controls: [{ key: "compact", label: "Compact rows", type: "toggle" }],
  },
  {
    slug: "stat-card",
    title: "Stat Card",
    category: "Cards & Surfaces",
    description: "Dashboard metric card with optional trend indicator.",
    sourcePath: "components/ui/stat-card.tsx",
    order: 80,
    tags: ["dashboard", "metrics"],
    initialState: { label: "Active users", value: "12,840", change: "+12.4%", trend: "up" },
    controls: [
      { key: "label", label: "Label", type: "text" },
      { key: "value", label: "Value", type: "text" },
      { key: "change", label: "Change", type: "text" },
      {
        key: "trend",
        label: "Trend",
        type: "select",
        options: [
          { label: "Up", value: "up" },
          { label: "Down", value: "down" },
          { label: "Neutral", value: "neutral" },
        ],
      },
    ],
  },
  {
    slug: "pricing-card",
    title: "Pricing Card",
    category: "Cards & Surfaces",
    description: "Marketing pricing tier card with feature list and CTA.",
    sourcePath: "components/ui/pricing-card.tsx",
    order: 85,
    tags: ["pricing", "marketing"],
    initialState: { name: "Pro", price: "$29", highlighted: true },
    controls: [
      { key: "name", label: "Plan name", type: "text" },
      { key: "price", label: "Price", type: "text" },
      { key: "highlighted", label: "Highlighted", type: "toggle" },
    ],
  },
  {
    slug: "toast",
    title: "Toast",
    category: "Overlays & Menus",
    description: "Animated toast notifications with success, error, and info variants.",
    sourcePath: "components/ui/toast.tsx",
    order: 50,
    tags: ["notification", "feedback"],
    initialState: { variant: "success", title: "Changes saved", description: "Your settings were updated successfully." },
    controls: [
      {
        key: "variant",
        label: "Variant",
        type: "select",
        options: [
          { label: "Default", value: "default" },
          { label: "Success", value: "success" },
          { label: "Error", value: "error" },
          { label: "Info", value: "info" },
        ],
      },
      { key: "title", label: "Title", type: "text" },
      { key: "description", label: "Description", type: "text" },
    ],
  },
  {
    slug: "context-menu",
    title: "Context Menu",
    category: "Overlays & Menus",
    description: "Right-click menu with nested items and checkbox options.",
    sourcePath: "components/ui/context-menu.tsx",
    order: 55,
    tags: ["menu", "context"],
    initialState: { hint: "Right click here" },
    controls: [{ key: "hint", label: "Hint text", type: "text" }],
  },
  {
    slug: "collapsible",
    title: "Collapsible",
    category: "Overlays & Menus",
    description: "Expandable section with smooth height animation.",
    sourcePath: "components/ui/collapsible.tsx",
    order: 60,
    tags: ["disclosure", "accordion"],
    initialState: { title: "Advanced settings", defaultOpen: false },
    controls: [
      { key: "title", label: "Title", type: "text" },
      { key: "defaultOpen", label: "Default open", type: "toggle" },
    ],
  },
  {
    slug: "stepper",
    title: "Stepper",
    category: "Layout & Navigation",
    description: "Multi-step progress indicator for wizards and onboarding flows.",
    sourcePath: "components/ui/stepper.tsx",
    order: 70,
    tags: ["wizard", "steps"],
    initialState: { currentStep: 1 },
    controls: [{ key: "currentStep", label: "Current step", type: "slider", min: 0, max: 2, step: 1 }],
  },
  {
    slug: "timeline",
    title: "Timeline",
    category: "Layout & Navigation",
    description: "Vertical activity timeline for logs, history, and changelogs.",
    sourcePath: "components/ui/timeline.tsx",
    order: 75,
    tags: ["history", "activity"],
    initialState: { itemCount: 3 },
    controls: [{ key: "itemCount", label: "Items shown", type: "slider", min: 1, max: 3, step: 1 }],
  },
  {
    slug: "footer",
    title: "Footer",
    category: "Layout & Navigation",
    description: "Site footer with brand, navigation links, and social link.",
    sourcePath: "components/ui/footer.tsx",
    order: 80,
    tags: ["layout", "footer"],
    initialState: { brand: "Aurora UI" },
    controls: [{ key: "brand", label: "Brand", type: "text" }],
  },
  {
    slug: "circular-text",
    title: "Circular Text",
    category: "Typography & Counters",
    description: "Text arranged in a spinning circle around a center point.",
    sourcePath: "components/ui/circular-text.tsx",
    order: 85,
    tags: ["text", "circular"],
    initialState: { text: "AURORA UI • BUILD BEAUTIFUL • ", radius: 80, spinDuration: 20 },
    controls: [
      { key: "text", label: "Text", type: "text" },
      { key: "radius", label: "Radius", type: "slider", min: 50, max: 120, step: 5 },
      { key: "spinDuration", label: "Spin (s)", type: "slider", min: 8, max: 40, step: 2 },
    ],
  },
  {
    slug: "text-scramble",
    title: "Text Scramble",
    category: "Typography & Counters",
    description: "Decrypt-style character scramble animation on load.",
    sourcePath: "components/ui/text-scramble.tsx",
    order: 90,
    tags: ["text", "scramble"],
    initialState: { text: "ACCESS GRANTED", duration: 1200 },
    controls: [
      { key: "text", label: "Text", type: "text" },
      { key: "duration", label: "Duration (ms)", type: "slider", min: 600, max: 2400, step: 100 },
    ],
  },
  {
    slug: "light-rays",
    title: "Light Rays",
    category: "Backgrounds & Ambient Effects",
    description: "Radiating light beams from a central glow point.",
    sourcePath: "components/ui/light-rays.tsx",
    order: 55,
    tags: ["background", "light"],
    initialState: { count: 8, color: "#a855f7" },
    controls: [
      { key: "count", label: "Ray count", type: "slider", min: 4, max: 16, step: 1 },
      { key: "color", label: "Color", type: "color" },
    ],
  },
  {
    slug: "floating-orbs",
    title: "Floating Orbs",
    category: "Backgrounds & Ambient Effects",
    description: "Soft blurred gradient orbs that drift behind hero headlines and CTAs.",
    sourcePath: "components/ui/floating-orbs.tsx",
    order: 56,
    tags: ["background", "hero", "orbs"],
    initialState: { count: 4, color: "#a855f7", speed: 1, blur: 80 },
    controls: [
      { key: "count", label: "Orb count", type: "slider", min: 2, max: 8, step: 1 },
      { key: "color", label: "Color", type: "color" },
      { key: "speed", label: "Speed", type: "slider", min: 0.5, max: 2, step: 0.1 },
      { key: "blur", label: "Blur", type: "slider", min: 40, max: 120, step: 10 },
    ],
  },
  {
    slug: "perspective-grid",
    title: "Perspective Grid",
    category: "Backgrounds & Ambient Effects",
    description: "A receding floor grid for tech and SaaS hero sections.",
    sourcePath: "components/ui/perspective-grid.tsx",
    order: 57,
    tags: ["background", "hero", "grid"],
    initialState: { color: "#a855f7", speed: 1, fade: true },
    controls: [
      { key: "color", label: "Color", type: "color" },
      { key: "speed", label: "Speed", type: "slider", min: 0.5, max: 2, step: 0.1 },
      { key: "fade", label: "Fade mask", type: "toggle" },
    ],
  },
  {
    slug: "gradient-mesh",
    title: "Gradient Mesh",
    category: "Backgrounds & Ambient Effects",
    description: "Animated color blobs that blend into a living mesh backdrop.",
    sourcePath: "components/ui/gradient-mesh.tsx",
    order: 58,
    tags: ["background", "hero", "gradient"],
    initialState: { colorFrom: "#a855f7", colorTo: "#22d3ee", speed: 1 },
    controls: [
      { key: "colorFrom", label: "From", type: "color" },
      { key: "colorTo", label: "To", type: "color" },
      { key: "speed", label: "Speed", type: "slider", min: 0.5, max: 2, step: 0.1 },
    ],
  },
  {
    slug: "beams-background",
    title: "Beams Background",
    category: "Backgrounds & Ambient Effects",
    description: "Vertical light beams that pulse behind landing page heroes.",
    sourcePath: "components/ui/beams-background.tsx",
    order: 59,
    tags: ["background", "hero", "beams"],
    initialState: { count: 8, color: "#a855f7", speed: 1 },
    controls: [
      { key: "count", label: "Beam count", type: "slider", min: 4, max: 14, step: 1 },
      { key: "color", label: "Color", type: "color" },
      { key: "speed", label: "Speed", type: "slider", min: 0.5, max: 2, step: 0.1 },
    ],
  },
  {
    slug: "hero-waves",
    title: "Hero Waves",
    category: "Backgrounds & Ambient Effects",
    description: "Layered SVG waves anchored to the bottom of hero sections.",
    sourcePath: "components/ui/hero-waves.tsx",
    order: 60,
    tags: ["background", "hero", "waves"],
    initialState: { color: "#a855f7", speed: 1, layers: 3 },
    controls: [
      { key: "color", label: "Color", type: "color" },
      { key: "speed", label: "Speed", type: "slider", min: 0.5, max: 2, step: 0.1 },
      { key: "layers", label: "Layers", type: "slider", min: 1, max: 4, step: 1 },
    ],
  },
  {
    slug: "starfield-background",
    title: "Starfield",
    category: "Backgrounds & Ambient Effects",
    description: "Twinkling star field for dark hero backgrounds and launch pages.",
    sourcePath: "components/ui/starfield-background.tsx",
    order: 61,
    tags: ["background", "hero", "stars"],
    initialState: { count: 80, color: "#ffffff", speed: 1 },
    controls: [
      { key: "count", label: "Star count", type: "slider", min: 30, max: 150, step: 10 },
      { key: "color", label: "Color", type: "color" },
      { key: "speed", label: "Speed", type: "slider", min: 0.5, max: 2, step: 0.1 },
    ],
  },
  {
    slug: "webgl-globe",
    title: "WebGL Globe",
    category: "3D & WebGL",
    description: "Interactive dotted globe rendered with react-three-fiber — spin, glow, and depth for platform heroes.",
    sourcePath: "components/ui/webgl-globe.tsx",
    order: 10,
    tags: ["3d", "webgl", "globe"],
    initialState: { count: 1500, color: "#a855f7", speed: 1, size: 0.025 },
    controls: [
      { key: "count", label: "Dot count", type: "slider", min: 500, max: 3000, step: 100 },
      { key: "color", label: "Color", type: "color" },
      { key: "speed", label: "Speed", type: "slider", min: 0.5, max: 2, step: 0.1 },
      { key: "size", label: "Dot size", type: "slider", min: 0.01, max: 0.05, step: 0.005 },
    ],
  },
  {
    slug: "webgl-particle-field",
    title: "WebGL Particle Field",
    category: "3D & WebGL",
    description: "Depth-filled particle cloud with cursor parallax — a lightweight WebGL hero backdrop.",
    sourcePath: "components/ui/webgl-particle-field.tsx",
    order: 30,
    tags: ["3d", "webgl", "particles", "hero"],
    initialState: { count: 1200, color: "#a855f7", speed: 1, spread: 6 },
    controls: [
      { key: "count", label: "Particle count", type: "slider", min: 400, max: 2500, step: 100 },
      { key: "color", label: "Color", type: "color" },
      { key: "speed", label: "Speed", type: "slider", min: 0.5, max: 2, step: 0.1 },
      { key: "spread", label: "Spread", type: "slider", min: 4, max: 10, step: 0.5 },
    ],
  },
];